on:
  push:
    branches:
      - master

env:
  REPOSITORY_ID: ${{github.event.repository.name}}
  ALERTS_CHANNEL_ID: G0146DEF2Q2

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ true }} # If true, job will always run. To stop job from running, set to false

    steps:
      - name: Job started
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ env.ALERTS_CHANNEL_ID }}
          status: Started
          color: warning
      - uses: actions/checkout@v2
      - name: Setup variables
        run: |
          echo "::set-env name=COMMIT_SHA_SHORT::$(git rev-parse --short HEAD)"
          echo "::set-env name=BRANCH_NAME::$(git rev-parse --abbrev-ref HEAD)"
      - id: build
        name: Build docker image
        env:
          DOCKER_BUILD_TAG: ${{ env.REPOSITORY_ID }}-${{ env.BRANCH_NAME }}
        run: |
          echo "Building image with tag: ${{ env.DOCKER_BUILD_TAG }}"
          docker build -f Dockerfile -t ${{ env.DOCKER_BUILD_TAG }} .
          echo "::set-env name=DOCKER_BUILD_TAG::${{ env.DOCKER_BUILD_TAG }}"

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - id: push
        name: Push to Google Container Registry
        env:
          DOCKER_PUSH_TAG: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.DOCKER_BUILD_TAG }}:${{ env.COMMIT_SHA_SHORT }}
        run: |
          echo "Publishing image with tag: ${{ env.DOCKER_PUSH_TAG }}"
          docker tag ${{ env.DOCKER_BUILD_TAG }} ${{ env.DOCKER_PUSH_TAG }}
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
          docker push ${{ env.DOCKER_PUSH_TAG }}
          echo "::set-env name=DOCKER_PUSH_TAG::${{ env.DOCKER_PUSH_TAG }}"

      - name: Job succeeded
        if: ${{ success() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ env.ALERTS_CHANNEL_ID }}
          status: "```Status: Successful\nCommit Sha: ${{env.COMMIT_SHA_SHORT}}\nImage: ${{ env.DOCKER_PUSH_TAG }}```"
          color: good

      - name: Job failed
        if: ${{ failure() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ env.ALERTS_CHANNEL_ID }}
          status: FAILED
          color: danger

      - name: Job cancelled
        if: ${{ cancelled() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ env.ALERTS_CHANNEL_ID }}
          status: Cancelled
          color: danger
